.github/ISSUE_TEMPLATE/config.yml:
  contact_links:
    - name: â“ Help and Support RocketChat Channel
      url: https://community.appuio.ch
      about: Please ask and answer questions here. ğŸ¥

LICENSE:
  year: 2021
  holder: VSHN
