.github/ISSUE_TEMPLATE/config.yml:
  contact_links:
    - name: â“ Help and Support RocketChat Channel
      url: https://community.appuio.ch
      about: Please ask and answer questions here. ğŸ¥

.github/workflows/test.yaml:
  unit-tests: false
  component-compile: true

LICENSE:
  year: 2021
  holder: VSHN

.gitignore:
  # Add additional lines to the `.gitignore` file
  additionalEntries: []
